custom_file_path:
  variable: source/_data/variables.styl
  style: source/_data/styles.styl

scheme: Gemini

menu:
  home: / || fa fa-home
  about: /about/ || fa fa-user
  tags: /tags/ || fa fa-tags
  categories: /categories/ || fa fa-th
  archives: /archives/ || fa fa-archive

sidebar:
  display: always

toc:
  number: false

post_meta:
  updated_at:
    enable: false

mobile_layout_economy: true

codeblock:
  theme:
    light: github
    dark: github
  copy_button:
    enable: true

github_banner:
  enable: true
  permalink: https://github.com/gonwan

font:
  enable: true
  global:
    external: false
    family: -apple-system, BlinkMacSystemFont, "Segoe UI", "Noto Sans", Helvetica,Arial, sans-serif, "Apple Color Emoji", "Segoe UI Emoji"
  codes:
    external: false
    family: ui-monospace, SFMono-Regular, SF Mono, Menlo, Consolas, Liberation Mono, monospace

motion:
  enable: false

local_search:
  enable: true
  top_n_per_article: 1
  unescape: false
  preload: false

google_analytics:
  tracking_id: G-35NDVTJNTY
  only_pageview: false
