custom_file_path:
  variable: source/_data/variables.styl
  style: source/_data/styles.styl

scheme: Gemini

menu:
  home: / || fa fa-home
  about: /about/ || fa fa-user
  tags: /tags/ || fa fa-tags
  categories: /categories/ || fa fa-th
  archives: /archives/ || fa fa-archive

sidebar:
  display: always

toc:
  number: false

post_meta:
  item_text: false
  updated_at:
    enable: false

symbols_count_time:
  separated_meta: true
  item_text_total: false

tag_icon: true

mobile_layout_economy: true

codeblock:
  theme:
    light: github
    dark: github
  copy_button:
    enable: true

github_banner:
  enable: true
  permalink: https://github.com/gonwan

font:
  enable: true
  global:
    external: false
    family: -apple-system, BlinkMacSystemFont, "Segoe UI", "Noto Sans", Helvetica,Arial, sans-serif, "Apple Color Emoji", "Segoe UI Emoji"
  codes:
    external: false
    family: ui-monospace, SFMono-Regular, SF Mono, Menlo, Consolas, Liberation Mono, monospace

motion:
  enable: false

google_analytics:
  tracking_id: G-35NDVTJNTY
  only_pageview: false

local_search:
  enable: true
  top_n_per_article: 1
  unescape: false
  preload: false

giscus:
  enable: true
  repo: gonwan/blog
  repo_id: R_kgDOOushVA
  category: General
  category_id: DIC_kwDOOushVM4CqjX-
  mapping: pathname
  reactions_enabled: 1
  emit_metadata: 0
  theme: light
  lang: en
  input_position: bottom
  loading: lazy
